Meteor.startup ->

	Logo = [
				{name: "Staples", img_name: "logo_en.png", fr_img_name: "logo_fr.png"}
			]

	Carousel = [
				{name: "Ink-helper", img_name: "copy_print_en.jpg", id: 1, fr_name: "Chercheur d'encre", fr_img_name: "copy_print_fr.png"},
				{name: "Virtual Store", img_name: "copy_print_en.jpg", id: 2, fr_name: "Magasin Virtuel", fr_img_name: "copy_print_fr.png"},
				{name: "Copy Center", img_name: "copy_print_en.jpg", id: 3, fr_name: "Centre de Copies", fr_img_name: "copy_print_fr.png"},
				{name: "Tech Center", img_name: "copy_print_en.jpg", id: 4, fr_name: "Centre technique", fr_img_name: "copy_print_fr.png"},
				{name: "Rate your experience", img_name: "copy_print_en.jpg", id: 5, fr_name: "Évaluez votre expérience", fr_img_name: "copy_print_fr.png"}
			]

	Manuf = [
				{name: "Brother", logo: "brother.png", systemId: "BR"},
				{name: "Canon", logo: "canon.png", systemId: "CA"},
				{name: "Dell", logo: "dell.png", systemId: "DE"},
				{name: "Epson", logo: "epson.png", systemId: "EP"},
				{name: "HP", logo: "hp.png", systemId: "HP"},
				{name: "Lexmark", logo: "lexmark.png", systemId: "LE"},
				{name: "Panasonic", logo: "panasonic.png", systemId: "PA"},
				{name: "Samsung", logo: "samsung.png", systemId: "SA"},
				{name: "Staples", logo: "staples.png", systemId: "OB"},
				{name: "Sharp", logo: "sharp.png", systemId: "SH"},
				{name: "Xerox", logo: "xerox.png", systemId: "XE"}
			]
	Model = [
				{name: "Artisan", manufacturer: "EP", systemId: "ART"},
				{name: "Expression", manufacturer: "EP", systemId: "EXP"},
				{name: "Stylus", manufacturer: "EP", systemId: "STY"},
				{name: "WorkForce", manufacturer: "EP", systemId: "WKF"},
				{name: "Deskjet", manufacturer: "HP", systemId: "DSK"},
				{name: "ENVY", manufacturer: "HP", systemId: "ENV"},
				{name: "OfficeJet", manufacturer: "HP", systemId: "OFJ"},
				{name: "PageWide", manufacturer: "HP", systemId: "PAW"},
				{name: "PhotoSmart", manufacturer: "HP", systemId: "PHS"},
				{name: "Laser Jet", manufacturer: "HP", systemId: "LAJ"},
				{name: "Color Laser Jet", manufacturer: "HP", systemId: "CLJ"}
			]

	Printer = [
				{manufacturer: "EP", model: "ART", number: "1430", comp_blk_ink: ["79"], comp_clr_ink: ["79"], description: "Epson Artisan 1430", systemId: "EPART1430", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "50", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Artisan 50", systemId: "EPART0050", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "700", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 700", systemId: "EPART0700", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "710", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 710", systemId: "EPART0710", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "725", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 725", systemId: "EPART0725", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "730", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 730", systemId: "EPART0730", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "800", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 800", systemId: "EPART0800", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "810", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 810", systemId: "EPART0810", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "835", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 835", systemId: "EPART0835", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "ART", number: "837", comp_blk_ink: ["98"], comp_clr_ink: ["98", "99"], description: "Epson Artisan 837", systemId: "EPART0837", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "ET-2500", comp_blk_ink: ["664"], comp_clr_ink: ["664"], description: "Epson Expression ET-2500", systemId: "EPEXP2500", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "ET-2550", comp_blk_ink: ["664"], comp_clr_ink: ["664"], description: "Epson Expression ET-2550", systemId: "EPEXP2550", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-200", comp_blk_ink: ["200", "200XL"], comp_clr_ink: ["200", "200XL"], description: "Epson Expression XP-200", systemId: "EPEXP0200", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-300", comp_blk_ink: ["200", "200XL"], comp_clr_ink: ["200", "200XL"], description: "Epson Expression XP-300", systemId: "EPEXP0300", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-310", comp_blk_ink: ["200", "200XL"], comp_clr_ink: ["200", "200XL"], description: "Epson Expression XP-310", systemId: "EPEXP0310", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-320", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson Expression XP-320", systemId: "EPEXP0320", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-330", comp_blk_ink: ["288", "288XL"], comp_clr_ink: ["288", "288XL"], description: "Epson Expression XP-330", systemId: "EPEXP0330", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-400", comp_blk_ink: ["200", "200XL"], comp_clr_ink: ["200", "200XL"], description: "Epson Expression XP-400", systemId: "EPEXP0400", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-410", comp_blk_ink: ["200", "200XL"], comp_clr_ink: ["200", "200XL"], description: "Epson Expression XP-410", systemId: "EPEXP0410", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-420", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson Expression XP-420", systemId: "EPEXP0420", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-424", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson Expression XP-424", systemId: "EPEXP0424", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-430", comp_blk_ink: ["288", "288XL"], comp_clr_ink: ["288", "288XL"], description: "Epson Expression XP-430", systemId: "EPEXP0430", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-434", comp_blk_ink: ["288", "288XL"], comp_clr_ink: ["288", "288XL"], description: "Epson Expression XP-434", systemId: "EPEXP0434", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-850", comp_blk_ink: ["277", "277XL"], comp_clr_ink: ["277", "277XL"], description: "Epson Expression XP-850", systemId: "EPEXP0850", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-860", comp_blk_ink: ["277", "277XL"], comp_clr_ink: ["277", "277XL"], description: "Epson Expression XP-860", systemId: "EPEXP0860", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-950", comp_blk_ink: ["277", "277XL"], comp_clr_ink: ["277", "277XL"], description: "Epson Expression XP-950", systemId: "EPEXP0950", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-960", comp_blk_ink: ["277", "277XL"], comp_clr_ink: ["277", "277XL"], description: "Epson Expression XP-960", systemId: "EPEXP0960", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-520", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-520", systemId: "EPEXP0520", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-530", comp_blk_ink: ["410", "410XL"], comp_clr_ink: ["410", "410XL"], description: "Epson Expression XP-530", systemId: "EPEXP0530", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-600", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-600", systemId: "EPEXP0600", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-610", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-610", systemId: "EPEXP0610", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-620", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-620", systemId: "EPEXP0620", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-630", comp_blk_ink: ["410", "410XL"], comp_clr_ink: ["410", "410XL"], description: "Epson Expression XP-630", systemId: "EPEXP0630", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-800", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-800", systemId: "EPEXP0800", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-810", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-810", systemId: "EPEXP0810", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-820", comp_blk_ink: ["273", "273XL"], comp_clr_ink: ["273", "273XL"], description: "Epson Expression XP-820", systemId: "EPEXP0820", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EXP", number: "XP-830", comp_blk_ink: ["410", "410XL"], comp_clr_ink: ["410", "410XL"], description: "Epson Expression XP-830", systemId: "EPEXP0830", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "C120", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus C120", systemId: "EPSTYC120", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "C68", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus C68", systemId: "EPSTY0C68", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "C88", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus C88", systemId: "EPSTY0C88", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX3810", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus CX3810", systemId: "EPSTY3810", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX4200", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus CX4200", systemId: "EPSTY4200", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX4450", comp_blk_ink: ["88"], comp_clr_ink: ["88"], description: "Epson Stylus CX4450", systemId: "EPSTY4450", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX4800", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus CX4800", systemId: "EPSTY4800", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX5000", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus CX5000", systemId: "EPSTY5000", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX5800F", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus CX5800F", systemId: "EPSTY5800", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX6000", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus CX6000", systemId: "EPSTY6000", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX7000F", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus CX7000F", systemId: "EPSTY7000", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX7450", comp_blk_ink: ["69", "88"], comp_clr_ink: ["68", "69", "88"], description: "Epson Stylus CX7450", systemId: "EPSTY7450", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX7800", comp_blk_ink: ["60"], comp_clr_ink: ["60"], description: "Epson Stylus CX7800", systemId: "EPSTY7800", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX8400", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus CX8400", systemId: "EPSTY8400", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "CX9400", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson Stylus CX9400", systemId: "EPSTY9400", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "N10", comp_blk_ink: ["69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus N10", systemId: "EPSTY0N10", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX100", comp_blk_ink: ["69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX100", systemId: "EPSTYN100", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX115", comp_blk_ink: ["69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX115", systemId: "EPSTYN115", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX125", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson Stylus NX125", systemId: "EPSTYN125", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX130", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson Stylus NX130", systemId: "EPSTYN130", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX200", comp_blk_ink: ["69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX200", systemId: "EPSTYN200", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "EP", number: "NX215", comp_blk_ink: ["68", "69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX215", systemId: "EPSTYN215", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX230", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson Stylus NX230", systemId: "EPSTYN230", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX300", comp_blk_ink: ["68", "69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX300", systemId: "EPSTYN300", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX330", comp_blk_ink: ["124", "126"], comp_clr_ink: ["124", "126"], description: "Epson Stylus NX330", systemId: "EPSTYN330", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX400", comp_blk_ink: ["68", "69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX400", systemId: "EPSTYN400", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX415", comp_blk_ink: ["68", "69", "88"], comp_clr_ink: ["69", "88"], description: "Epson Stylus NX415", systemId: "EPSTYN415", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX420", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson Stylus NX420", systemId: "EPSTYN420", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX430", comp_blk_ink: ["124", "126"], comp_clr_ink: ["124", "126"], description: "Epson Stylus NX430", systemId: "EPSTYN430", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX510", comp_blk_ink: ["68", "69", "97"], comp_clr_ink: ["68", "69"], description: "Epson Stylus NX510", systemId: "EPSTYN510", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX515", comp_blk_ink: ["68", "69", "97"], comp_clr_ink: ["68", "69"], description: "Epson Stylus NX515", systemId: "EPSTYN515", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX530", comp_blk_ink: ["125", "127"], comp_clr_ink: ["125", "127"], description: "Epson Stylus NX530", systemId: "EPSTYN530", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "NX625", comp_blk_ink: ["125", "127"], comp_clr_ink: ["125", "127"], description: "Epson Stylus NX625", systemId: "EPSTYN625", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "Photo 1400", comp_blk_ink: ["79"], comp_clr_ink: ["79"], description: "Epson Stylus Photo 1400", systemId: "EPSTY1400", ink: "Ink jet", fr_ink: "Jet d'encre"}
				{manufacturer: "EP", model: "STY", number: "Photo R260", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo R260", systemId: "EPSTYR260", ink: "Ink jet", fr_ink: "Jet d'encre"}, 
				{manufacturer: "EP", model: "STY", number: "Photo R280", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo R280", systemId: "EPSTYR280", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "Photo R380", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo R380", systemId: "EPSTYR380", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "Photo RX580", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo RX580", systemId: "EPSTYR580", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "Photo RX595", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo RX595", systemId: "EPSTYR595", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "STY", number: "Photo RX680", comp_blk_ink: ["77", "78"], comp_clr_ink: ["77", "78"], description: "Epson Stylus Photo RX680", systemId: "EPSTYR680", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "30", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson WorkForce 30", systemId: "EPWKF0030", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "310", comp_blk_ink: ["68", "69"], comp_clr_ink: ["68", "69"], description: "Epson WorkForce 310", systemId: "EPWKF0310", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "320", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson WorkForce 320", systemId: "EPWKF0320", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "323", comp_blk_ink: ["124", "125"], comp_clr_ink: ["124", "125"], description: "Epson WorkForce 323", systemId: "EPWKF0323", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "40", comp_blk_ink: ["68", "69", "97"], comp_clr_ink: ["68", "69"], description: "Epson WorkForce 40", systemId: "EPWKF0040", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "435", comp_blk_ink: ["124", "126"], comp_clr_ink: ["124", "126"], description: "Epson WorkForce 435", systemId: "EPWKF0435", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "520", comp_blk_ink: ["125", "126"], comp_clr_ink: ["125", "126"], description: "Epson WorkForce 520", systemId: "EPWKF0520", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "545", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 545", systemId: "EPWKF0545", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "60", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 60", systemId: "EPWKF0060", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "600", comp_blk_ink: ["68", "69", "97"], comp_clr_ink: ["68", "69"], description: "Epson WorkForce 600", systemId: "EPWKF0600", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "610", comp_blk_ink: ["68", "69", "97"], comp_clr_ink: ["68", "69"], description: "Epson WorkForce 610", systemId: "EPWKF0610", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "630", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 630", systemId: "EPWKF0630", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "633", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 633", systemId: "EPWKF0633", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "645", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 645", systemId: "EPWKF0645", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "840", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 840", systemId: "EPWKF0840", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "845", comp_blk_ink: ["126", "127"], comp_clr_ink: ["126", "127"], description: "Epson WorkForce 845", systemId: "EPWKF0845", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "ET-4500", comp_blk_ink: ["664"], comp_clr_ink: ["664"], description: "Epson WorkForce ET-4500", systemId: "EPWKF4500", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "ET-4550", comp_blk_ink: ["774"], comp_clr_ink: ["664"], description: "Epson WorkForce ET-4550", systemId: "EPWKF4550", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-4630", comp_blk_ink: ["786", "786XL"], comp_clr_ink: ["786", "786XL"], description: "Epson WorkForce Pro WF-4630", systemId: "EPWKF4630", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-4640", comp_blk_ink: ["786", "786XL"], comp_clr_ink: ["786", "786XL"], description: "Epson WorkForce Pro WF-4640", systemId: "EPWKF4640", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-5110", comp_blk_ink: ["786", "786XL", "788XXL"], comp_clr_ink: ["786", "786XL", "788XXL"], description: "Epson WorkForce Pro WF-5110", systemId: "EPWKF5110", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-5190", comp_blk_ink: ["786", "786XL", "788XXL"], comp_clr_ink: ["786", "786XL", "788XXL"], description: "Epson WorkForce Pro WF-5190", systemId: "EPWKF5190", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-5620", comp_blk_ink: ["786", "786XL", "788XXL"], comp_clr_ink: ["786", "786XL", "788XXL"], description: "Epson WorkForce Pro WF-5620", systemId: "EPWKF5620", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-5690", comp_blk_ink: ["786", "786XL", "788XXL"], comp_clr_ink: ["786", "786XL", "788XXL"], description: "Epson WorkForce Pro WF-5690", systemId: "EPWKF5690", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-6090", comp_blk_ink: ["748", "748XL", "748XXL"], comp_clr_ink: ["748", "748XL", "748XXL"], description: "Epson WorkForce Pro WF-6090", systemId: "EPWKF6090", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-6530", comp_blk_ink: ["748", "748XL"], comp_clr_ink: ["748", "748XL"], description: "Epson WorkForce Pro WF-6530", systemId: "EPWKF6530", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-6590", comp_blk_ink: ["748", "748XL", "748XXL"], comp_clr_ink: ["748", "748XL", "748XXL"], description: "Epson WorkForce Pro WF-6590", systemId: "EPWKF6590", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-8090", comp_blk_ink: ["748", "748XL", "748XXL"], comp_clr_ink: ["748", "748XL", "748XXL"], description: "Epson WorkForce Pro WF-8090", systemId: "EPWKF8090", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "Pro WF-8590", comp_blk_ink: ["748", "748XL", "748XXL"], comp_clr_ink: ["748", "748XL", "748XXL"], description: "Epson WorkForce Pro WF-8590", systemId: "EPWKF8590", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "WF-2630", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson WorkForce WF-2630", systemId: "EPWKF2630", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "WF-2650", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson WorkForce WF-2650", systemId: "EPWKF2650", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "EP", model: "WKF", number: "WF-2660", comp_blk_ink: ["220", "220XL"], comp_clr_ink: ["220", "220XL"], description: "Epson WorkForce WF-2660", systemId: "EPWKF2660", ink: "Ink jet", fr_ink: "Jet d'encre"},

				{manufacturer: "HP", model: "DSK", number: "1000-1056", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 1000-1056", systemId: "HPDSK10XX", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "1110-1112", comp_blk_ink: ["63", "63XL"], comp_clr_ink: ["63", "63XL"], description: "HP Deskjet 1110-1112", systemId: "HPDSK111X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "1510-1517", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 1510-1517", systemId: "HPDSK151X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "2050-2054", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 2050-2054", systemId: "HPDSK205X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "2130-2134", comp_blk_ink: ["63", "63XL"], comp_clr_ink: ["63", "63XL"], description: "HP Deskjet 2130-2134", systemId: "HPDSK213X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "2510-2514", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 2510-2514", systemId: "HPDSK251X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "2540-2549", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 2540-2549", systemId: "HPDSK254X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3000", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3000", systemId: "HPDSK3000", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3050-3054", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3050-3054", systemId: "HPDSK305X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3055", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3055", systemId: "HPDSK3055", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3056", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3056", systemId: "HPDSK3056", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3059", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3059", systemId: "HPDSK3059", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3070", comp_blk_ink: ["564", "564XL"], comp_clr_ink: ["564", "564XL"], description: "HP Deskjet 3070", systemId: "HPDSK3070", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3510-3512", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3510-3512", systemId: "HPDSK351X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3522", comp_blk_ink: ["564", "564XL"], comp_clr_ink: ["564", "564XL"], description: "HP Deskjet 3522", systemId: "HPDSK3522", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3526", comp_blk_ink: ["564", "564XL"], comp_clr_ink: ["564", "564XL"], description: "HP Deskjet 3526", systemId: "HPDSK3526", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "3630-3634", comp_blk_ink: ["61", "61XL"], comp_clr_ink: ["61", "61XL"], description: "HP Deskjet 3630-3634", systemId: "HPDSK363X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "6943", comp_blk_ink: ["96"], comp_clr_ink: ["97", "99", "100"], description: "HP Deskjet 6943", systemId: "HPDSK6943", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "6980-6988", comp_blk_ink: ["96"], comp_clr_ink: ["97", "99", "100"], description: "HP Deskjet 6980-6988", systemId: "HPDSK698X", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "D1520-1568", comp_blk_ink: ["21"], comp_clr_ink: ["22"], description: "HP Deskjet D1520-1568", systemId: "HPDSK15XX", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "D2320-2368", comp_blk_ink: ["21"], comp_clr_ink: ["22", "58"], description: "HP Deskjet D2320-2368", systemId: "HPDSK23XX", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "D2430-2468", comp_blk_ink: ["21"], comp_clr_ink: ["22", "58"], description: "HP Deskjet D2430-2468", systemId: "HPDSK24XX", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "D2530-2568", comp_blk_ink: ["60", "60XL"], comp_clr_ink: ["60", "60XL"], description: "HP Deskjet D2530-2568", systemId: "HPDSK25XX", ink: "Ink jet", fr_ink: "Jet d'encre"},
				{manufacturer: "HP", model: "DSK", number: "D2645-2680", comp_blk_ink: ["60", "60XL"], comp_clr_ink: ["60", "60XL"], description: "HP Deskjet D2645-2680", systemId: "HPDSK26XX", ink: "Ink jet", fr_ink: "Jet d'encre"}
			]

	Cartridge = [
				{manuf: "EP", number: "79", type: "jet", color: "black", yield: "470", desc: "Epson black cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 noir Epson", id: "EPJETBK79"},
				{manuf: "EP", number: "79", type: "jet", color: "light cyan", yield: "810", desc: "Epson light cyan cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 cyan p\u00E2le Epson", id: "EPJETLC79"},
				{manuf: "EP", number: "79", type: "jet", color: "yellow", yield: "810", desc: "Epson yellow cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 jaune Epson", id: "EPJETYE79"},
				{manuf: "EP", number: "79", type: "jet", color: "light magenta", yield: "810", desc: "Epson light magenta cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 magenta p\u00E2le Epson", id: "EPJETLM79"},
				{manuf: "EP", number: "79", type: "jet", color: "magenta", yield: "810", desc: "Epson magenta cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 magenta Epson", id: "EPJETMA79"},
				{manuf: "EP", number: "79", type: "jet", color: "cyan", yield: "810", desc: "Epson cyan cartridge number 79", fr_desc: "Cartouche num\u00E9ro 79 cyan Epson", id: "EPJETCY79"},
				{manuf: "EP", number: "77", type: "jet", color: "black", yield: "540", desc: "Epson black cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 noir Epson", id: "EPJETBK77"},
				{manuf: "EP", number: "77", type: "jet", color: "cyan", yield: "860", desc: "Epson cyan cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 cyan Epson", id: "EPJETCY77"},
				{manuf: "EP", number: "77", type: "jet", color: "magenta", yield: "860", desc: "Epson magenta cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 magenta Epson", id: "EPJETMA77"},
				{manuf: "EP", number: "77", type: "jet", color: "yellow", yield: "860", desc: "Epson yellow cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 jaune Epson", id: "EPJETYE77"},
				{manuf: "EP", number: "77", type: "jet", color: "light cyan", yield: "860", desc: "Epson light cyan cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 cyan p\u00E2le Epson", id: "EPJETLC77"},
				{manuf: "EP", number: "77", type: "jet", color: "light magenta", yield: "860", desc: "Epson light magenta cartridge number 77", fr_desc: "Cartouche num\u00E9ro 77 magenta p\u00E2le Epson", id: "EPJETLM77"},
				{manuf: "EP", number: "78", type: "jet", color: "black", yield: "330", desc: "Epson black cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 noir Epson", id: "EPJETBK78"},
				{manuf: "EP", number: "78", type: "jet", color: "cyan", yield: "525", desc: "Epson cyan cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 cyan Epson", id: "EPJETCY78"},
				{manuf: "EP", number: "78", type: "jet", color: "magenta", yield: "525", desc: "Epson magenta cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 magenta Epson", id: "EPJETMA78"},
				{manuf: "EP", number: "78", type: "jet", color: "yellow", yield: "525", desc: "Epson yellow cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 jaune Epson", id: "EPJETYE78"},
				{manuf: "EP", number: "78", type: "jet", color: "light cyan", yield: "525", desc: "Epson light cyan cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 cyan p\u00E2le Epson", id: "EPJETLC78"},
				{manuf: "EP", number: "78", type: "jet", color: "light magenta", yield: "525", desc: "Epson light magenta cartridge number 78", fr_desc: "Cartouche num\u00E9ro 78 magenta p\u00E2le Epson", id: "EPJETLM78"},
				{manuf: "EP", number: "98", type: "jet", color: "black", yield: "520", desc: "Epson black cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 noir Epson", id: "EPJETBK98"},
				{manuf: "EP", number: "98", type: "jet", color: "cyan", yield: "805", desc: "Epson cyan cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 cyan Epson", id: "EPJETCY98"},
				{manuf: "EP", number: "98", type: "jet", color: "magenta", yield: "805", desc: "Epson magenta cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 magenta Epson", id: "EPJETMA98"},
				{manuf: "EP", number: "98", type: "jet", color: "yellow", yield: "805", desc: "Epson yellow cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 jaune Epson", id: "EPJETYE98"},
				{manuf: "EP", number: "98", type: "jet", color: "light cyan", yield: "805", desc: "Epson light cyan cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 cyan p\u00E2le Epson", id: "EPJETLC98"},
				{manuf: "EP", number: "98", type: "jet", color: "light magenta", yield: "805", desc: "Epson light magenta cartridge number 98", fr_desc: "Cartouche num\u00E9ro 98 magenta p\u00E2le Epson", id: "EPJETLM98"},
				{manuf: "EP", number: "99", type: "jet", color: "cyan", yield: "510", desc: "Epson cyan cartridge number 99", fr_desc: "Cartouche num\u00E9ro 99 cyan Epson", id: "EPJETCY99"},
				{manuf: "EP", number: "99", type: "jet", color: "magenta", yield: "510", desc: "Epson magenta cartridge number 99", fr_desc: "Cartouche num\u00E9ro 99 magenta Epson", id: "EPJETMA99"},
				{manuf: "EP", number: "99", type: "jet", color: "yellow", yield: "510", desc: "Epson yellow cartridge number 99", fr_desc: "Cartouche num\u00E9ro 99 jaune Epson", id: "EPJETYE99"},
				{manuf: "EP", number: "99", type: "jet", color: "light cyan", yield: "510", desc: "Epson light cyan cartridge number 99", fr_desc: "Cartouche num\u00E9ro 99 cyan p\u00E2le Epson", id: "EPJETLC99"},
				{manuf: "EP", number: "99", type: "jet", color: "light magenta", yield: "510", desc: "Epson light magenta cartridge number 99", fr_desc: "Cartouche num\u00E9ro 99 magenta p\u00E2le Epson", id: "EPJETLM99"},
				{manuf: "EP", number: "664", type: "jet", color: "black", yield: "4000", desc: "Epson black Ecotank ink bottle number 664", fr_desc: "Bouteille d'encre Ecotank num\u00E9ro 664 noir Epson", id: "EPJETBK664"},
				{manuf: "EP", number: "664", type: "jet", color: "cyan", yield: "6500", desc: "Epson cyan Ecotank ink bottle number 664", fr_desc: "Bouteille d'encre Ecotank num\u00E9ro 664 cyan Epson", id: "EPJETCY664"},
				{manuf: "EP", number: "664", type: "jet", color: "magenta", yield: "6500", desc: "Epson magenta Ecotank ink bottle number 664", fr_desc: "Bouteille d'encre Ecotank num\u00E9ro 664 magenta Epson", id: "EPJETMA664"},
				{manuf: "EP", number: "664", type: "jet", color: "yellow", yield: "6500", desc: "Epson yellow Ecotank ink bottle number 664", fr_desc: "Bouteille d'encre Ecotank num\u00E9ro 664 jaune Epson", id: "EPJETYE664"},
				{manuf: "EP", number: "200", type: "jet", color: "black", yield: "175", desc: "Epson black cartridge number 200", fr_desc: "Cartouche num\u00E9ro 200 noir Epson", id: "EPJETBK200"},
				{manuf: "EP", number: "200", type: "jet", color: "cyan", yield: "165", desc: "Epson cyan cartridge number 200", fr_desc: "Cartouche num\u00E9ro 200 cyan Epson", id: "EPJETCY200"},
				{manuf: "EP", number: "200", type: "jet", color: "magenta", yield: "165", desc: "Epson magenta cartridge number 200", fr_desc: "Cartouche num\u00E9ro 200 magenta Epson", id: "EPJETMA200"},
				{manuf: "EP", number: "200", type: "jet", color: "yellow", yield: "165", desc: "Epson yellow cartridge number 200", fr_desc: "Cartouche num\u00E9ro 200 jaune Epson", id: "EPJETYE200"},
				{manuf: "EP", number: "200XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 200XL", fr_desc: "Cartouche num\u00E9ro 200XL noir Epson", id: "EPJETBK200X"},
				{manuf: "EP", number: "200XL", type: "jet", color: "cyan", yield: "450", desc: "Epson cyan cartridge number 200XL", fr_desc: "Cartouche num\u00E9ro 200XL cyan Epson", id: "EPJETCY200X"},
				{manuf: "EP", number: "200XL", type: "jet", color: "magenta", yield: "450", desc: "Epson magenta cartridge number 200XL", fr_desc: "Cartouche num\u00E9ro 200XL magenta Epson", id: "EPJETMA200X"},
				{manuf: "EP", number: "200XL", type: "jet", color: "yellow", yield: "450", desc: "Epson yellow cartridge number 200XL", fr_desc: "Cartouche num\u00E9ro 200XL jaune Epson", id: "EPJETYE200X"},
				{manuf: "EP", number: "220", type: "jet", color: "black", yield: "175", desc: "Epson black cartridge number 220", fr_desc: "Cartouche num\u00E9ro 220 noir Epson", id: "EPJETBK220"},
				{manuf: "EP", number: "220", type: "jet", color: "cyan", yield: "165", desc: "Epson cyan cartridge number 220", fr_desc: "Cartouche num\u00E9ro 220 cyan Epson", id: "EPJETCY220"},
				{manuf: "EP", number: "220", type: "jet", color: "magenta", yield: "165", desc: "Epson magenta cartridge number 220", fr_desc: "Cartouche num\u00E9ro 220 magenta Epson", id: "EPJETMA220"},
				{manuf: "EP", number: "220", type: "jet", color: "yellow", yield: "165", desc: "Epson yellow cartridge number 220", fr_desc: "Cartouche num\u00E9ro 220 jaune Epson", id: "EPJETYE220"},
				{manuf: "EP", number: "220XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 220XL", fr_desc: "Cartouche num\u00E9ro 220XL noir", id: "EPJETBK220X"},
				{manuf: "EP", number: "220XL", type: "jet", color: "cyan", yield: "450", desc: "Epson cyan cartridge number 220XL", fr_desc: "Cartouche num\u00E9ro 220XL cyan Epson", id: "EPJETCY220X"},
				{manuf: "EP", number: "220XL", type: "jet", color: "magenta", yield: "450", desc: "Epson magenta cartridge number 220XL", fr_desc: "Cartouche num\u00E9ro 220XL magenta Epson", id: "EPJETMA220X"},
				{manuf: "EP", number: "220XL", type: "jet", color: "yellow", yield: "450", desc: "Epson yellow cartridge number 220XL", fr_desc: "Cartouche num\u00E9ro 220XL jaune Epson", id: "EPJETYE220X"},
				{manuf: "EP", number: "288", type: "jet", color: "black", yield: "175", desc: "Epson black cartridge number 288", fr_desc: "Cartouche num\u00E9ro 288 noir Epson", id: "EPJETBK288"},
				{manuf: "EP", number: "288", type: "jet", color: "cyan", yield: "165", desc: "Epson cyan cartridge number 288", fr_desc: "Cartouche num\u00E9ro 288 cyan Epson", id: "EPJETCY288"},
				{manuf: "EP", number: "288", type: "jet", color: "magenta", yield: "165", desc: "Epson magenta cartridge number 288", fr_desc: "Cartouche num\u00E9ro 288 magenta Epson", id: "EPJETMA288"},
				{manuf: "EP", number: "288", type: "jet", color: "yellow", yield: "165", desc: "Epson yellow cartridge number 288", fr_desc: "Cartouche num\u00E9ro 288 jaune Epson", id: "EPJETYE288"},
				{manuf: "EP", number: "288XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 288XL", fr_desc: "Cartouche num\u00E9ro 288XL noir Epson", id: "EPJETBK288X"},
				{manuf: "EP", number: "288XL", type: "jet", color: "cyan", yield: "450", desc: "Epson cyan cartridge number 288XL", fr_desc: "Cartouche num\u00E9ro 288XL cyan Epson", id: "EPJETCY288X"},
				{manuf: "EP", number: "288XL", type: "jet", color: "magenta", yield: "450", desc: "Epson magenta cartridge number 288XL", fr_desc: "Cartouche num\u00E9ro 288XL magenta Epson", id: "EPJETMA288X"},
				{manuf: "EP", number: "288XL", type: "jet", color: "yellow", yield: "450", desc: "Epson yellow cartridge number 288XL", fr_desc: "Cartouche num\u00E9ro 288XL jaune Epson", id: "EPJETYE288X"},
				{manuf: "EP", number: "277", type: "jet", color: "black", yield: "240", desc: "Epson black cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 noir Epson", id: "EPJETBK277"},
				{manuf: "EP", number: "277", type: "jet", color: "cyan", yield: "360", desc: "Epson cyan cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 cyan Epson", id: "EPJETCY277"},
				{manuf: "EP", number: "277", type: "jet", color: "magenta", yield: "360", desc: "Epson magenta cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 magenta Epson", id: "EPJETMA277"},
				{manuf: "EP", number: "277", type: "jet", color: "yellow", yield: "360", desc: "Epson yellow cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 jaune Epson", id: "EPJETYE277"},
				{manuf: "EP", number: "277", type: "jet", color: "light cyan", yield: "360", desc: "Epson light cyan cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 cyan p\u00E2le Epson", id: "EPJETLC277"},
				{manuf: "EP", number: "277", type: "jet", color: "light magenta", yield: "360", desc: "Epson light magenta cartridge number 277", fr_desc: "Cartouche num\u00E9ro 277 magenta p\u00E2le Epson", id: "EPJETLM277"},
				{manuf: "EP", number: "277XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL noir Epson", id: "EPJETBK277X"},
				{manuf: "EP", number: "277XL", type: "jet", color: "cyan", yield: "740", desc: "Epson cyan cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL cyan Epson", id: "EPJETCY277X"},
				{manuf: "EP", number: "277XL", type: "jet", color: "magenta", yield: "740", desc: "Epson magenta cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL magenta Epson", id: "EPJETMA277X"},
				{manuf: "EP", number: "277XL", type: "jet", color: "yellow", yield: "740", desc: "Epson yellow cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL jaune Epson", id: "EPJETYE277X"},
				{manuf: "EP", number: "277XL", type: "jet", color: "light cyan", yield: "740", desc: "Epson light cyan cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL cyan p\u00E2le Epson", id: "EPJETLC277X"},
				{manuf: "EP", number: "277XL", type: "jet", color: "light magenta", yield: "740", desc: "Epson light magenta cartridge number 277XL", fr_desc: "Cartouche num\u00E9ro 277XL magenta p\u00E2le Epson", id: "EPJETLM277X"},
				{manuf: "EP", number: "273", type: "jet", color: "black", yield: "250", desc: "Epson black cartridge number 273", fr_desc: "Cartouche num\u00E9ro 273 noir Epson", id: "EPJETBK273"},
				{manuf: "EP", number: "273", type: "jet", color: "cyan", yield: "300", desc: "Epson cyan cartridge number 273", fr_desc: "Cartouche num\u00E9ro 273 cyan Epson", id: "EPJETCY273"},
				{manuf: "EP", number: "273", type: "jet", color: "magenta", yield: "300", desc: "Epson magenta cartridge number 273", fr_desc: "Cartouche num\u00E9ro 273 magenta Epson", id: "EPJETMA273"},
				{manuf: "EP", number: "273", type: "jet", color: "yellow", yield: "300", desc: "Epson yellow cartridge number 273", fr_desc: "Cartouche num\u00E9ro 273 jaune Epson", id: "EPJETYE273"},
				{manuf: "EP", number: "273", type: "jet", color: "photo black", yield: "200", desc: "Epson photo black cartridge number 273", fr_desc: "Cartouche num\u00E9ro 273 photo noir Epson", id: "EPJETPB273"},
				{manuf: "EP", number: "273XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 273XL", fr_desc: "Cartouche num\u00E9ro 273XL noir Epson", id: "EPJETBK273X"},
				{manuf: "EP", number: "273XL", type: "jet", color: "cyan", yield: "650", desc: "Epson cyan cartridge number 273XL", fr_desc: "Cartouche num\u00E9ro 273XL cyan Epson", id: "EPJETCY273X"},
				{manuf: "EP", number: "273XL", type: "jet", color: "magenta", yield: "650", desc: "Epson magenta cartridge number 273XL", fr_desc: "Cartouche num\u00E9ro 273XL magenta Epson", id: "EPJETMA273X"},
				{manuf: "EP", number: "273XL", type: "jet", color: "yellow", yield: "650", desc: "Epson yellow cartridge number 273XL", fr_desc: "Cartouche num\u00E9ro 273XL jaune Epson", id: "EPJETYE273X"},
				{manuf: "EP", number: "273XL", type: "jet", color: "photo black", yield: "400", desc: "Epson photo black cartridge number 273XL", fr_desc: "Cartouche num\u00E9ro 273XL photo noir Epson", id: "EPJETPB273X"},
				{manuf: "EP", number: "410", type: "jet", color: "black", yield: "250", desc: "Epson black cartridge number 410", fr_desc: "Cartouche num\u00E9ro 410 noir Epson", id: "EPJETBK410"},
				{manuf: "EP", number: "410", type: "jet", color: "cyan", yield: "300", desc: "Epson cyan cartridge number 410", fr_desc: "Cartouche num\u00E9ro 410 cyan Epson", id: "EPJETCY410"},
				{manuf: "EP", number: "410", type: "jet", color: "magenta", yield: "300", desc: "Epson magenta cartridge number 410", fr_desc: "Cartouche num\u00E9ro 410 magenta Epson", id: "EPJETMA410"},
				{manuf: "EP", number: "410", type: "jet", color: "yellow", yield: "300", desc: "Epson yellow cartridge number 410", fr_desc: "Cartouche num\u00E9ro 410 jaune Epson", id: "EPJETYE410"},
				{manuf: "EP", number: "410", type: "jet", color: "photo black", yield: "200", desc: "Epson photo black cartridge number 410", fr_desc: "Cartouche num\u00E9ro 410 photo noir Epson", id: "EPJETPB410"},
				{manuf: "EP", number: "410XL", type: "jet", color: "black", yield: "500", desc: "Epson black cartridge number 410XL", fr_desc: "Cartouche num\u00E9ro 410XL noir Epson", id: "EPJETBK410X"},
				{manuf: "EP", number: "410XL", type: "jet", color: "cyan", yield: "650", desc: "Epson cyan cartridge number 410XL", fr_desc: "Cartouche num\u00E9ro 410XL cyan Epson", id: "EPJETCY410X"},
				{manuf: "EP", number: "410XL", type: "jet", color: "magenta", yield: "650", desc: "Epson magenta cartridge number 410XL", fr_desc: "Cartouche num\u00E9ro 410XL magenta Epson", id: "EPJETMA410X"},
				{manuf: "EP", number: "410XL", type: "jet", color: "yellow", yield: "650", desc: "Epson yellow cartridge number 410XL", fr_desc: "Cartouche num\u00E9ro 410XL jaune Epson", id: "EPJETYE410X"},
				{manuf: "EP", number: "410XL", type: "jet", color: "photo black", yield: "400", desc: "Epson photo black cartridge number 410XL", fr_desc: "Cartouche num\u00E9ro 410XL photo noir Epson", id: "EPJETPB410X"},
				{manuf: "EP", number: "68", type: "jet", color: "black", yield: "390", desc: "Epson black cartridge number 68", fr_desc: "Cartouche num\u00E9ro 68 noir Epson", id: "EPJETBK68"},
				{manuf: "EP", number: "68", type: "jet", color: "cyan", yield: "500", desc: "Epson cyan cartridge number 68", fr_desc: "Cartouche num\u00E9ro 68 cyan Epson", id: "EPJETCY68"},
				{manuf: "EP", number: "68", type: "jet", color: "magenta", yield: "500", desc: "Epson magenta cartridge number 68", fr_desc: "Cartouche num\u00E9ro 68 magenta Epson", id: "EPJETMA68"},
				{manuf: "EP", number: "68", type: "jet", color: "yellow", yield: "500", desc: "Epson yellow cartridge number 68", fr_desc: "Cartouche num\u00E9ro 68 jaune Epson", id: "EPJETYE68"},
				{manuf: "EP", number: "69", type: "jet", color: "black", yield: "240", desc: "Epson black cartridge number 69", fr_desc: "Cartouche num\u00E9ro 69 noir Epson", id: "EPJETBK69"},
				{manuf: "EP", number: "69", type: "jet", color: "cyan", yield: "335", desc: "Epson cyan cartridge number 69", fr_desc: "Cartouche num\u00E9ro 69 cyan Epson", id: "EPJETCY69"},
				{manuf: "EP", number: "69", type: "jet", color: "magenta", yield: "335", desc: "Epson magenta cartridge number 69", fr_desc: "Cartouche num\u00E9ro 69 magenta Epson", id: "EPJETMA69"},
				{manuf: "EP", number: "69", type: "jet", color: "yellow", yield: "335", desc: "Epson yellow cartridge number 69", fr_desc: "Cartouche num\u00E9ro 69 jaune Epson", id: "EPJETYE69"},
				{manuf: "EP", number: "60", type: "jet", color: "black", yield: "400", desc: "Epson black cartridge number 60", fr_desc: "Cartouche num\u00E9ro 60 noir Epson", id: "EPJETBK60"},
				{manuf: "EP", number: "60", type: "jet", color: "cyan", yield: "600", desc: "Epson cyan cartridge number 60", fr_desc: "Cartouche num\u00E9ro 60 cyan Epson", id: "EPJETCY60"},
				{manuf: "EP", number: "60", type: "jet", color: "magenta", yield: "600", desc: "Epson magenta cartridge number 60", fr_desc: "Cartouche num\u00E9ro 60 magenta Epson", id: "EPJETMA60"},
				{manuf: "EP", number: "60", type: "jet", color: "yellow", yield: "600", desc: "Epson yellow cartridge number 60", fr_desc: "Cartouche num\u00E9ro 60 jaune Epson", id: "EPJETYE60"},
				{manuf: "EP", number: "88", type: "jet", color: "black", yield: "180", desc: "Epson black cartridge number 88", fr_desc: "Cartouche num\u00E9ro 88 noir Epson", id: "EPJETBK88"},
				{manuf: "EP", number: "88", type: "jet", color: "cyan", yield: "175", desc: "Epson cyan cartridge number 88", fr_desc: "Cartouche num\u00E9ro 88 cyan Epson", id: "EPJETCY88"},
				{manuf: "EP", number: "88", type: "jet", color: "magenta", yield: "175", desc: "Epson magenta cartridge number 88", fr_desc: "Cartouche num\u00E9ro 88 magenta Epson", id: "EPJETMA88"},
				{manuf: "EP", number: "88", type: "jet", color: "yellow", yield: "175", desc: "Epson yellow cartridge number 88", fr_desc: "Cartouche num\u00E9ro 88 jaune Epson", id: "EPJETYE88"},
				{manuf: "EP", number: "124", type: "jet", color: "black", yield: "170", desc: "Epson black cartridge number 124", fr_desc: "Cartouche num\u00E9ro 124 noir Epson", id: "EPJETBK124"},
				{manuf: "EP", number: "124", type: "jet", color: "cyan", yield: "175", desc: "Epson cyan cartridge number 124", fr_desc: "Cartouche num\u00E9ro 124 cyan Epson", id: "EPJETCY124"},
				{manuf: "EP", number: "124", type: "jet", color: "magenta", yield: "175", desc: "Epson magenta cartridge number 124", fr_desc: "Cartouche num\u00E9ro 124 magenta Epson", id: "EPJETMA124"},
				{manuf: "EP", number: "124", type: "jet", color: "yellow", yield: "175", desc: "Epson yellow cartridge number 124", fr_desc: "Cartouche num\u00E9ro 124 jaune Epson", id: "EPJETYE124"},
				{manuf: "EP", number: "125", type: "jet", color: "black", yield: "220", desc: "Epson black cartridge number 125", fr_desc: "Cartouche num\u00E9ro 125 noir Epson", id: "EPJETBK125"},
				{manuf: "EP", number: "125", type: "jet", color: "cyan", yield: "335", desc: "Epson cyan cartridge number 125", fr_desc: "Cartouche num\u00E9ro 125 cyan Epson", id: "EPJETCY125"},
				{manuf: "EP", number: "125", type: "jet", color: "magenta", yield: "335", desc: "Epson magenta cartridge number 125", fr_desc: "Cartouche num\u00E9ro 125 magenta Epson", id: "EPJETMA125"},
				{manuf: "EP", number: "125", type: "jet", color: "yellow", yield: "335", desc: "Epson yellow cartridge number 125", fr_desc: "Cartouche num\u00E9ro 125 jaune Epson", id: "EPJETYE125"},
				{manuf: "EP", number: "126", type: "jet", color: "black", yield: "370", desc: "Epson black cartridge number 126", fr_desc: "Cartouche num\u00E9ro 126 noir Epson", id: "EPJETBK126"},
				{manuf: "EP", number: "126", type: "jet", color: "cyan", yield: "450", desc: "Epson cyan cartridge number 126", fr_desc: "Cartouche num\u00E9ro 126 cyan Epson", id: "EPJETCY126"},
				{manuf: "EP", number: "126", type: "jet", color: "magenta", yield: "450", desc: "Epson magenta cartridge number 126", fr_desc: "Cartouche num\u00E9ro 126 magenta Epson", id: "EPJETMA126"},
				{manuf: "EP", number: "126", type: "jet", color: "yellow", yield: "450", desc: "Epson yellow cartridge number 126", fr_desc: "Cartouche num\u00E9ro 126 jaune Epson", id: "EPJETYE126"},
				{manuf: "EP", number: "97", type: "jet", color: "black", yield: "850", desc: "Epson black cartridge number 97", fr_desc: "Cartouche num\u00E9ro 97 noir Epson", id: "EPJETBK97"},
				{manuf: "EP", number: "127", type: "jet", color: "black", yield: "945", desc: "Epson black cartridge number 127", fr_desc: "Cartouche num\u00E9ro 127 noir Epson", id: "EPJETBK127"},
				{manuf: "EP", number: "127", type: "jet", color: "cyan", yield: "755", desc: "Epson cyan cartridge number 127", fr_desc: "Cartouche num\u00E9ro 127 cyan Epson", id: "EPJETCY127"},
				{manuf: "EP", number: "127", type: "jet", color: "magenta", yield: "755", desc: "Epson magenta cartridge number 127", fr_desc: "Cartouche num\u00E9ro 127 magenta Epson", id: "EPJETMA127"},
				{manuf: "EP", number: "127", type: "jet", color: "yellow", yield: "755", desc: "Epson yellow cartridge number 127", fr_desc: "Cartouche num\u00E9ro 127 jaune Epson", id: "EPJETYE127"},
				{manuf: "EP", number: "774", type: "jet", color: "black", yield: "6000", desc: "Epson black Ecotank ink bottle number 774", fr_desc: "Bouteille d'encre Ecotank num\u00E9ro 774 noir Epson", id: "EPJETBK774"},
				{manuf: "EP", number: "786", type: "jet", color: "black", yield: "900", desc: "Epson black cartridge number 786", fr_desc: "Cartouche num\u00E9ro 786 noir Epson", id: "EPJETBK786"},
				{manuf: "EP", number: "786", type: "jet", color: "cyan", yield: "800", desc: "Epson cyan cartridge number 786", fr_desc: "Cartouche num\u00E9ro 786 cyan Epson", id: "EPJETCY786"},
				{manuf: "EP", number: "786", type: "jet", color: "magenta", yield: "800", desc: "Epson magenta cartridge number 786", fr_desc: "Cartouche num\u00E9ro 786 magenta Epson", id: "EPJETMA786"},
				{manuf: "EP", number: "786", type: "jet", color: "yellow", yield: "800", desc: "Epson yellow cartridge number 786", fr_desc: "Cartouche num\u00E9ro 786 jaune Epson", id: "EPJETYE786"},
				{manuf: "EP", number: "786XL", type: "jet", color: "black", yield: "2600", desc: "Epson black cartridge number 786XL", fr_desc: "Cartouche num\u00E9ro 786XL noir Epson", id: "EPJETBK786X"},
				{manuf: "EP", number: "786XL", type: "jet", color: "cyan", yield: "2000", desc: "Epson cyan cartridge number 786XL", fr_desc: "Cartouche num\u00E9ro 786XL cyan Epson", id: "EPJETCY786X"},
				{manuf: "EP", number: "786XL", type: "jet", color: "magenta", yield: "2000", desc: "Epson magenta cartridge number 786XL", fr_desc: "Cartouche num\u00E9ro 786XL magenta Epson", id: "EPJETMA786X"},
				{manuf: "EP", number: "786XL", type: "jet", color: "yellow", yield: "2000", desc: "Epson yellow cartridge number 786XL", fr_desc: "Cartouche num\u00E9ro 786XL jaune Epson", id: "EPJETYE786X"},
				{manuf: "EP", number: "788XXL", type: "jet", color: "black", yield: "4000", desc: "Epson black cartridge number 788XXL", fr_desc: "Cartouche num\u00E9ro 788XXL noir Epson", id: "EPJETBK788X"},
				{manuf: "EP", number: "788XXL", type: "jet", color: "cyan", yield: "4000", desc: "Epson cyan cartridge number 788XXL", fr_desc: "Cartouche num\u00E9ro 788XXL cyan Epson", id: "EPJETCY788X"},
				{manuf: "EP", number: "788XXL", type: "jet", color: "magenta", yield: "4000", desc: "Epson magenta cartridge number 788XXL", fr_desc: "Cartouche num\u00E9ro 788XXL magenta Epson", id: "EPJETMA788X"},
				{manuf: "EP", number: "788XXL", type: "jet", color: "yellow", yield: "4000", desc: "Epson yellow cartridge number 788XXL", fr_desc: "Cartouche num\u00E9ro 788XXL jaune Epson", id: "EPJETYE788X"},
				{manuf: "EP", number: "748", type: "jet", color: "black", yield: "2500", desc: "Epson black cartridge number 748", fr_desc: "Cartouche num\u00E9ro 748 noir Epson", id: "EPJETBK748"},
				{manuf: "EP", number: "748", type: "jet", color: "cyan", yield: "1500", desc: "Epson cyan cartridge number 748", fr_desc: "Cartouche num\u00E9ro 748 cyan Epson", id: "EPJETCY748"},
				{manuf: "EP", number: "748", type: "jet", color: "magenta", yield: "1500", desc: "Epson magenta cartridge number 748", fr_desc: "Cartouche num\u00E9ro 748 magenta Epson", id: "EPJETMA748"},
				{manuf: "EP", number: "748", type: "jet", color: "yellow", yield: "1500", desc: "Epson yellow cartridge number 748", fr_desc: "Cartouche num\u00E9ro 748 jaune Epson", id: "EPJETYE748"},
				{manuf: "EP", number: "748XL", type: "jet", color: "black", yield: "5000", desc: "Epson black cartridge number 748XL", fr_desc: "Cartouche num\u00E9ro 748XL noir Epson", id: "EPJETBK748X"},
				{manuf: "EP", number: "748XL", type: "jet", color: "cyan", yield: "4000", desc: "Epson cyan cartridge number 748XL", fr_desc: "Cartouche num\u00E9ro 748XL cyan Epson", id: "EPJETCY748X"},
				{manuf: "EP", number: "748XL", type: "jet", color: "magenta", yield: "4000", desc: "Epson magenta cartridge number 748XL", fr_desc: "Cartouche num\u00E9ro 748XL magenta Epson", id: "EPJETMA748X"},
				{manuf: "EP", number: "748XL", type: "jet", color: "yellow", yield: "4000", desc: "Epson yellow cartridge number 748XL", fr_desc: "Cartouche num\u00E9ro 748XL jaune Epson", id: "EPJETYE748X"},
				{manuf: "EP", number: "748XXL", type: "jet", color: "black", yield: "10000", desc: "Epson black cartridge number 748XXL", fr_desc: "Cartouche num\u00E9ro 748XXL noir Epson", id: "EPJETBK748XX"},
				{manuf: "EP", number: "748XXL", type: "jet", color: "cyan", yield: "7000", desc: "Epson cyan cartridge number 748XXL", fr_desc: "Cartouche num\u00E9ro 748XXL cyan Epson", id: "EPJETCY748XX"},
				{manuf: "EP", number: "748XXL", type: "jet", color: "magenta", yield: "7000", desc: "Epson magenta cartridge number 748XXL", fr_desc: "Cartouche num\u00E9ro 748XXL magenta Epson", id: "EPJETMA748XX"},
				{manuf: "EP", number: "748XXL", type: "jet", color: "yellow", yield: "7000", desc: "Epson yellow cartridge number 748XXL", fr_desc: "Cartouche num\u00E9ro 748XXL jaune Epson", id: "EPJETYE748XX"}
			]
			
	if Manufacturers.find().count() is 0

		Manuf.forEach (manuf) ->
			Manufacturers.insert {name: manuf.name, logo: manuf.logo, systemId: manuf.systemId}

	if PrinterModels.find().count() is 0

		Model.forEach (model) ->
			PrinterModels.insert {name: model.name, manufacturer: model.manufacturer, systemId: model.systemId}

	if Printers.find().count() is 0

		Printer.forEach (printer) ->
			Printers.insertTranslations {manufacturer: printer.manufacturer, model: printer.model, model_number: printer.number, compatible_blk_ink: printer.comp_blk_ink, compatible_clr_ink: printer.comp_clr_ink, description: printer.description, img: printer.description + ".png", systemId: printer.systemId, ink_type: printer.ink}, fr: {ink_type: printer.fr_ink}

	if InkCartridges.find().count() is 0

		Cartridge.forEach (cartridge) ->
			InkCartridges.insertTranslations {manufacturer: cartridge.manuf, cartridge_number: cartridge.number, cartridge_type: cartridge.type, cartridge_color: cartridge.color, cartridge_yield: cartridge.yield, description: cartridge.desc, systemId: cartridge.id}, fr: {description: cartridge.fr_desc}

	if HomeCarousel.find().count() is 0

		Carousel.forEach (carousel) ->
			HomeCarousel.insertTranslations {name: carousel.name, img_name: carousel.img_name, id: carousel.id}, fr: {name: carousel.fr_name, img_name: carousel.fr_img_name}

	if Logos.find().count() is 0

		Logo.forEach (logo) ->
			Logos.insertTranslations {name: logo.name, img_name: logo.img_name}, fr: {img_name: logo.fr_img_name}